### ISSUE TITLE
Running multiple instances on a single machine

### ISSUE THREAD

**Issue by tzmhuang** [NVIDIA-Omniverse/OmniIsaacGymEnvs#63]
I wonder if it safe to run multiple independent training sessions on one machine? Would running multiple training instances at once cause any unexpected behavior? Thanks!

**Comment by kellyguo11** [comment]
Hi there, yes it is possible to run multiple independent training sessions. The limits in terms of how many processes you can run will depend on your hardware setup. You may see a decrease in performance in each process, since the resource is being split among the processes. Also make sure you are naming the experiments accordingly so that the checkpoints will not get overridden by different sessions.

**Comment by tzmhuang** [comment]
Got it thanks you!
