### ISSUE TITLE
Factory (Fast Contact for Robotic Assembly) integration

### ISSUE THREAD

**Issue by pt127** [NVIDIA-Omniverse/OmniIsaacGymEnvs#72]
Hello,

is there a  a plan when and if  "Factory" will be integrated in OmniIsaacGym as already for the Isaac Gym - Preview Release?
Is there a way to already use the controllers provided in Factory in the OmniIsaacGym envs?

Thanks

**Comment by iakinola23** [comment]
Hi,
Factory is already integrated into OmniIsaacGym, along with the associated robot [controllers](https://github.com/NVIDIA-Omniverse/OmniIsaacGymEnvs/blob/main/omniisaacgymenvs/tasks/factory/factory_control.py). The Pick task from Factory is already available [here](https://github.com/NVIDIA-Omniverse/OmniIsaacGymEnvs/blob/main/omniisaacgymenvs/tasks/factory/factory_task_nut_bolt_pick.py), and we anticipate releasing the remaining Factory tasks in the coming weeks.
We hope you'll find the Pick task and controllers already useful for your applications.
Best,

**Comment by pt127** [comment]
thanks for the answer. When i change the controller in the FactoryTaskNutBoltPick.yaml from joint_space_id  to task_space_impedance, there iss something wrong with the robot movement. The wrist is spinning around randonly. Is there a fix for that? Thanks

**Comment by iakinola23** [comment]
Hi,

I suspect that the issue may be due to the default gains for the task_space_impedance controller not being tuned for the robot model. I suggest adjusting the gains, particularly focusing on the rotational P/D gains. As a starting point, you can consider reducing the D gains by an order of magnitude.

Please give this a try and let us know if it improves the situation.

Best,
