### ISSUE TITLE
How to use the FactoryTasks?

### ISSUE THREAD

**Issue by sambaPython24** [NVIDIA-Omniverse/OmniIsaacGymEnvs#77]
I see that among the ```Available options in 'task':```we find 
```
FactoryBase
FactoryEnvNutBolt
FactoryTaskNutBoltPick
```
but you canot use them like e.g. FrankaCabinet. 

When I run the two last tasks, I find hydra errors of the form 
```
hydra.errors.MissingConfigException: Cannot find primary config '[path_to_OmniverseIsaacGym]/OmniIsaacGymEnvs/cfg/task'. Check that it's in your config search path.
```
while there are both ```FactoryEnvNutBolt.yaml``` and ```FactoryTaskNutBoltPick.yaml``` in the mentioned folder. 

Also, in ```[path_to_OmniverseIsaacGym]/OmniIsaacGymEnvs/omniisaacgymenvs/tasks/factory/factory_env_nut_bolt.py```
I had to reset the ``asset_info_path```file such that ```[path_to_OmniverseIsaacGym]/OmniIsaacGymEnvs/omniisaacgymenvs/tasks/factory/yaml/factory_asset_info_nut_bolt.yaml``` was found.

**Comment by iakinola23** [comment]
Hello,

Our code and config files are structured hierarchically to accommodate various tasks in Factory, such as Pick, Place, and Screw for the nut and bolt environment. We've created base classes like FactoryBase and FactoryEnvNutBolt, which FactoryTaskNutBoltPick and similar tasks inherit from.

You will be able to train policies for specific tasks (e.g., FactoryTaskNutBoltPick) rather than the base classes.

Kindly let us know if you have additional questions.

Best,
